---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: "{{ lookup('hashi_vault', 'secret=secret/Client2:password token=s.LkUxkO69qhqQDLrc8Y74ETyx  url=http://127.0.0.1:8200')}}"
