---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: "{{ lookup('hashi_vault', 'secret=kv/data/Client2/login:data')|json_query('Server1Password') 'token=s.LkUxkO69qhqQDLrc8Y74ETyx url=http://192.168.1.93:8200')}}"
