---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: "{{ lookup('hashi_vault', 'secret=secret/data/Client2:login token=s.LkUxkO69qhqQDLrc8Y74ETyx url=http://192.168.1.93:8200')}}"
