---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Vault that requires authentication via username and password
   debug:
      msg: "{{ lookup('hashi_vault', 'secret=secret/Client2:password token=s.LkUxkO69qhqQDLrc8Y74ETyx url=http://127.0.0.1:8200')"
